# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fbe69baf492e18efed1993612964e90952e0151257aae3f5fc833f5fecdc949a9836bf196e2a296fe7fa1473a3a3a89f41501060fa4825fff78028661ed0963

test:
  secret_key_base: 509efbbc380549939cb60e9560660e4ad70e2ae673a5f8902fe578de3e9e9cb0a2666633565f4e97a197118a2c4f1252fd04810d174b1371042a326c6d4dd70f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
